module.exports = [
    { path: "/dashboard/listAllProject", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/createProject", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/deleteProject", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/getProjectDetails", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/getProjectSummary", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/updateProjectDetails", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/getUsersCount", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/getDevicesCount", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/getFilesCount", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/listAllUsers", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/listAllDevices", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/listAllFiles", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/deleteFile", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/createModel", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/deleteModel", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/listAllModels", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/registerDevice", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/deleteDevice", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/addUser", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/pairDevice", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/unpairDevice", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/deleteAccount", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/enableCorsOnDomain", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/disableCorsOnDomain", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/getDocumentsCount", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/getDocuments", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/getCollectionsCount", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/listCollections", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/setProjectTag", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/getProjectHostingDetails", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/setDomain", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/disableHosting", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/listAccessKeys", input: {}, output: {success: {}, failure: {}} },
    { path: "/dashboard/generateAccessKey", input: {}, output: {success: {}, failure: {}} } ,
    { path: "/dashboard/deleteAccessKey", input: {}, output: {success: {}, failure: {}} },
];